# Generated by Django 4.1.5 on 2023-01-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
