# Generated by Django 4.1.5 on 2023-01-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
